<template>
    <div v-if="show" class="fixed inset-0 bg-black/60 dark:bg-black/80 flex items-center justify-center z-[1000] p-5" @click.self="handleClose">
        <div class="bg-bg-elevated rounded-xl w-full max-w-[800px] max-h-[90vh] overflow-y-auto shadow-xl border border-surface-border">
            <div class="flex justify-between items-center p-6 border-b border-surface-border sticky top-0 bg-bg-elevated z-10">
                <h2 class="text-xl font-semibold text-text-primary m-0">
                    {{ partner ? $t('partner.edit') : $t('partner.create') }}
                </h2>
                <button @click="handleClose" class="bg-transparent border-none text-text-secondary cursor-pointer p-1 rounded transition-all duration-200 hover:bg-surface-hover hover:text-text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="18" y1="6" x2="6" y2="18"/>
                        <line x1="6" y1="6" x2="18" y2="18"/>
                    </svg>
                </button>
            </div>

            <form @submit.prevent="handleSubmit" class="p-6">
                <!-- Code (Auto-generated) -->
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2">{{ $t('partner.code') }}</label>
                    <input
                        type="text"
                        :value="partner?.code || $t('partner.autoGenerated')"
                        disabled
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-tertiary text-text-disabled cursor-not-allowed"
                    />
                    <small class="block mt-1 text-xs text-text-tertiary">{{ $t('partner.codeHint') }}</small>
                </div>

                <!-- Type and Name -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="type">
                            {{ $t('partner.type') }} <span class="text-accent-error">*</span>
                        </label>
                        <select
                            id="type"
                            v-model="form.type"
                            required
                            class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary cursor-pointer transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light"
                            :class="errors.type ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                        >
                            <option value="customer">{{ $t('partner.typeCustomer') }}</option>
                            <option value="supplier">{{ $t('partner.typeSupplier') }}</option>
                            <option value="both">{{ $t('partner.typeBoth') }}</option>
                        </select>
                        <span v-if="errors.type" class="block mt-1 text-xs text-accent-error">{{ errors.type }}</span>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="name">
                            {{ $t('partner.name') }} <span class="text-accent-error">*</span>
                        </label>
                        <input
                            id="name"
                            v-model="form.name"
                            type="text"
                            :placeholder="$t('partner.namePlaceholder')"
                            required
                            class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.name ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                        />
                        <span v-if="errors.name" class="block mt-1 text-xs text-accent-error">{{ errors.name }}</span>
                    </div>
                </div>

                <!-- Legal Information -->
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="legal_name">
                            {{ $t('partner.legalName') }}
                        </label>
                        <input
                            id="legal_name"
                            v-model="form.legal_name"
                            type="text"
                            :placeholder="$t('partner.legalNamePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="tax_id">
                            {{ $t('partner.taxId') }}
                        </label>
                        <input
                            id="tax_id"
                            v-model="form.tax_id"
                            type="text"
                            :placeholder="$t('partner.taxIdPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="registration_number">
                        {{ $t('partner.registrationNumber') }}
                    </label>
                    <input
                        id="registration_number"
                        v-model="form.registration_number"
                        type="text"
                        :placeholder="$t('partner.registrationNumberPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                    />
                </div>

                <!-- Contact Information -->
                <h3 class="text-lg font-semibold text-text-primary mb-4 mt-6">{{ $t('partner.contactInformation') }}</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="email">
                            {{ $t('partner.email') }}
                        </label>
                        <input
                            id="email"
                            v-model="form.email"
                            type="email"
                            :placeholder="$t('partner.emailPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.email ? 'border-accent-error focus:ring-red-200' : ''"
                        />
                        <span v-if="errors.email" class="block mt-1 text-xs text-accent-error">{{ errors.email }}</span>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="phone">
                            {{ $t('partner.phone') }}
                        </label>
                        <input
                            id="phone"
                            v-model="form.phone"
                            type="tel"
                            :placeholder="$t('partner.phonePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="mobile">
                            {{ $t('partner.mobile') }}
                        </label>
                        <input
                            id="mobile"
                            v-model="form.mobile"
                            type="tel"
                            :placeholder="$t('partner.mobilePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="website">
                            {{ $t('partner.website') }}
                        </label>
                        <input
                            id="website"
                            v-model="form.website"
                            type="url"
                            :placeholder="$t('partner.websitePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.website ? 'border-accent-error focus:ring-red-200' : ''"
                        />
                        <span v-if="errors.website" class="block mt-1 text-xs text-accent-error">{{ errors.website }}</span>
                    </div>
                </div>

                <!-- Address -->
                <h3 class="text-lg font-semibold text-text-primary mb-4 mt-6">{{ $t('partner.address') }}</h3>
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="address">
                        {{ $t('partner.address') }}
                    </label>
                    <textarea
                        id="address"
                        v-model="form.address"
                        rows="2"
                        :placeholder="$t('partner.addressPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary resize-none"
                    ></textarea>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="city">
                            {{ $t('partner.city') }}
                        </label>
                        <input
                            id="city"
                            v-model="form.city"
                            type="text"
                            :placeholder="$t('partner.cityPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="state">
                            {{ $t('partner.state') }}
                        </label>
                        <input
                            id="state"
                            v-model="form.state"
                            type="text"
                            :placeholder="$t('partner.statePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="postal_code">
                            {{ $t('partner.postalCode') }}
                        </label>
                        <input
                            id="postal_code"
                            v-model="form.postal_code"
                            type="text"
                            :placeholder="$t('partner.postalCodePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="country">
                            {{ $t('partner.country') }}
                        </label>
                        <input
                            id="country"
                            v-model="form.country"
                            type="text"
                            :placeholder="$t('partner.countryPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                </div>

                <!-- Financial Information -->
                <h3 class="text-lg font-semibold text-text-primary mb-4 mt-6">{{ $t('partner.financialInformation') }}</h3>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="payment_terms">
                            {{ $t('partner.paymentTerms') }}
                        </label>
                        <input
                            id="payment_terms"
                            v-model="form.payment_terms"
                            type="text"
                            :placeholder="$t('partner.paymentTermsPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        />
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="credit_limit">
                            {{ $t('partner.creditLimit') }}
                        </label>
                        <input
                            id="credit_limit"
                            v-model.number="form.credit_limit"
                            type="number"
                            step="0.01"
                            min="0"
                            :placeholder="$t('partner.creditLimitPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.credit_limit ? 'border-accent-error focus:ring-red-200' : ''"
                        />
                        <span v-if="errors.credit_limit" class="block mt-1 text-xs text-accent-error">{{ errors.credit_limit }}</span>
                    </div>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="discount_percent">
                        {{ $t('partner.discountPercent') }}
                    </label>
                    <input
                        id="discount_percent"
                        v-model.number="form.discount_percent"
                        type="number"
                        step="0.01"
                        min="0"
                        max="100"
                        :placeholder="$t('partner.discountPercentPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        :class="errors.discount_percent ? 'border-accent-error focus:ring-red-200' : ''"
                    />
                    <span v-if="errors.discount_percent" class="block mt-1 text-xs text-accent-error">{{ errors.discount_percent }}</span>
                </div>

                <!-- Notes and Status -->
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="notes">
                        {{ $t('partner.notes') }}
                    </label>
                    <textarea
                        id="notes"
                        v-model="form.notes"
                        rows="3"
                        :placeholder="$t('partner.notesPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary resize-none"
                    ></textarea>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="status">
                        {{ $t('partner.status') }}
                    </label>
                    <div class="flex items-center gap-2">
                        <input
                            id="status"
                            v-model="form.status"
                            type="checkbox"
                            class="w-[18px] h-[18px] cursor-pointer"
                        />
                        <label for="status" class="text-sm text-text-secondary cursor-pointer">
                            {{ $t('partner.isActive') }}
                        </label>
                    </div>
                </div>

                <div class="flex justify-end gap-3 mt-6 pt-6 border-t border-surface-border">
                    <button type="button" @click="handleClose" class="px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                        {{ $t('common.cancel') }}
                    </button>
                    <button type="submit" class="px-5 py-2.5 border-none rounded-lg bg-gradient-to-br from-accent-primary to-accent-secondary text-text-inverse font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="partnerStore.loading">
                        <span v-if="partnerStore.loading">{{ $t('common.saving') }}...</span>
                        <span v-else>{{ partner ? $t('common.update') : $t('common.create') }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue';
import { usePartnerStore } from '@/stores/partner';
import { useToast } from '@/composables/useToast';
import { useI18n } from 'vue-i18n';

const props = defineProps({
    show: {
        type: Boolean,
        default: false
    },
    partner: {
        type: Object,
        default: null
    }
});

const emit = defineEmits(['close', 'saved']);

const partnerStore = usePartnerStore();
const { success, error } = useToast();
const { t } = useI18n();

const form = ref({
    type: 'customer',
    name: '',
    legal_name: '',
    tax_id: '',
    registration_number: '',
    email: '',
    phone: '',
    mobile: '',
    website: '',
    address: '',
    city: '',
    state: '',
    postal_code: '',
    country: '',
    payment_terms: '',
    credit_limit: 0,
    discount_percent: 0,
    status: true,
    notes: ''
});

const errors = ref({});

watch(() => props.partner, (newPartner) => {
    if (newPartner) {
        form.value = {
            type: newPartner.type || 'customer',
            name: newPartner.name || '',
            legal_name: newPartner.legal_name || '',
            tax_id: newPartner.tax_id || '',
            registration_number: newPartner.registration_number || '',
            email: newPartner.email || '',
            phone: newPartner.phone || '',
            mobile: newPartner.mobile || '',
            website: newPartner.website || '',
            address: newPartner.address || '',
            city: newPartner.city || '',
            state: newPartner.state || '',
            postal_code: newPartner.postal_code || '',
            country: newPartner.country || '',
            payment_terms: newPartner.payment_terms || '',
            credit_limit: newPartner.credit_limit || 0,
            discount_percent: newPartner.discount_percent || 0,
            status: newPartner.status !== undefined ? newPartner.status : true,
            notes: newPartner.notes || ''
        };
    } else {
        form.value = {
            type: 'customer',
            name: '',
            legal_name: '',
            tax_id: '',
            registration_number: '',
            email: '',
            phone: '',
            mobile: '',
            website: '',
            address: '',
            city: '',
            state: '',
            postal_code: '',
            country: '',
            payment_terms: '',
            credit_limit: 0,
            discount_percent: 0,
            status: true,
            notes: ''
        };
    }
    errors.value = {};
}, { immediate: true });

watch(() => props.show, (isShow) => {
    if (isShow && props.partner) {
        form.value = {
            type: props.partner.type || 'customer',
            name: props.partner.name || '',
            legal_name: props.partner.legal_name || '',
            tax_id: props.partner.tax_id || '',
            registration_number: props.partner.registration_number || '',
            email: props.partner.email || '',
            phone: props.partner.phone || '',
            mobile: props.partner.mobile || '',
            website: props.partner.website || '',
            address: props.partner.address || '',
            city: props.partner.city || '',
            state: props.partner.state || '',
            postal_code: props.partner.postal_code || '',
            country: props.partner.country || '',
            payment_terms: props.partner.payment_terms || '',
            credit_limit: props.partner.credit_limit || 0,
            discount_percent: props.partner.discount_percent || 0,
            status: props.partner.status !== undefined ? props.partner.status : true,
            notes: props.partner.notes || ''
        };
    } else if (isShow && !props.partner) {
        form.value = {
            type: 'customer',
            name: '',
            legal_name: '',
            tax_id: '',
            registration_number: '',
            email: '',
            phone: '',
            mobile: '',
            website: '',
            address: '',
            city: '',
            state: '',
            postal_code: '',
            country: '',
            payment_terms: '',
            credit_limit: 0,
            discount_percent: 0,
            status: true,
            notes: ''
        };
    }
    errors.value = {};
});

const handleClose = () => {
    emit('close');
    form.value = {
        type: 'customer',
        name: '',
        legal_name: '',
        tax_id: '',
        registration_number: '',
        email: '',
        phone: '',
        mobile: '',
        website: '',
        address: '',
        city: '',
        state: '',
        postal_code: '',
        country: '',
        payment_terms: '',
        credit_limit: 0,
        discount_percent: 0,
        status: true,
        notes: ''
    };
    errors.value = {};
};

const handleSubmit = async () => {
    errors.value = {};

    if (!form.value.name.trim()) {
        errors.value.name = t('partner.nameRequired');
        return;
    }

    const partnerData = { ...form.value };
    
    // Clean empty strings to null
    Object.keys(partnerData).forEach(key => {
        if (partnerData[key] === '') {
            partnerData[key] = null;
        }
    });

    let result;
    if (props.partner) {
        result = await partnerStore.updatePartner(props.partner.id, partnerData);
    } else {
        result = await partnerStore.createPartner(partnerData);
    }

    if (result.success) {
        success(props.partner ? t('partner.updated') : t('partner.created'));
        emit('saved');
    } else {
        error(result.error || (props.partner ? t('partner.updateFailed') : t('partner.createFailed')));
        if (result.errors) {
            errors.value = result.errors;
        }
    }
};
</script>

