<?php

namespace Database\Factories;

use App\Models\Warehouse;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Warehouse>
 */
class WarehouseFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Warehouse::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $types = ['warehouse', 'store', 'tank'];
        
        return [
            'title' => $this->faker->words(2, true) . ' ' . ucfirst($this->faker->randomElement($types)),
            'isprincipal' => $this->faker->boolean(20), // 20% chance of being principal
            'inchargeOf' => User::inRandomOrder()->first()?->id ?? null,
            'type' => $this->faker->randomElement($types),
            // Note: 'code' is auto-generated by the model, so we don't set it here
        ];
    }

    /**
     * Indicate that the warehouse is principal.
     */
    public function principal(): static
    {
        return $this->state(fn (array $attributes) => [
            'isprincipal' => true,
        ]);
    }

    /**
     * Indicate that the warehouse is a warehouse type.
     */
    public function warehouse(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'warehouse',
        ]);
    }

    /**
     * Indicate that the warehouse is a store type.
     */
    public function store(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'store',
        ]);
    }

    /**
     * Indicate that the warehouse is a tank type.
     */
    public function tank(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'tank',
        ]);
    }
}

