<template>
    <div class="w-full">
        <div class="flex justify-between items-center mb-6">
            <h1 class="text-3xl font-bold text-text-primary m-0">{{ $t('product.edit') }}</h1>
            <router-link to="/app/products" class="flex items-center gap-2 px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M19 12H5M12 19l-7-7 7-7"/>
                </svg>
                <span>{{ $t('common.cancel') }}</span>
            </router-link>
        </div>

        <div v-if="loading" class="text-center p-10 text-text-tertiary">
            <span>{{ $t('common.loading') }}</span>
        </div>

        <div v-else-if="!product" class="text-center p-10 text-text-tertiary">
            <span>{{ $t('common.noData') }}</span>
        </div>

        <div v-else class="bg-bg-elevated rounded-xl shadow-md border border-surface-border p-6">
            <form @submit.prevent="handleSubmit">
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2">{{ $t('product.code') }}</label>
                    <input
                        type="text"
                        :value="product.code || $t('product.autoGenerated')"
                        disabled
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-tertiary text-text-disabled cursor-not-allowed"
                    />
                    <small class="block mt-1 text-xs text-text-tertiary">{{ $t('product.codeHint') }}</small>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="name">
                        {{ $t('product.name') }} <span class="text-accent-error">*</span>
                    </label>
                    <input
                        id="name"
                        v-model="form.name"
                        type="text"
                        :placeholder="$t('product.namePlaceholder')"
                        required
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        :class="errors.name ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    />
                    <span v-if="errors.name" class="block mt-1 text-xs text-accent-error">{{ errors.name }}</span>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="category_id">
                            {{ $t('product.category') }}
                        </label>
                        <select
                            id="category_id"
                            v-model="form.category_id"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary cursor-pointer transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light"
                            :class="errors.category_id ? 'border-accent-error' : ''"
                        >
                            <option value="">{{ $t('product.selectCategory') }}</option>
                            <option v-for="category in categories" :key="category.id" :value="category.id">{{ category.title }}</option>
                        </select>
                        <span v-if="errors.category_id" class="block mt-1 text-xs text-accent-error">{{ errors.category_id }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="brand_id">
                            {{ $t('product.brand') }}
                        </label>
                        <select
                            id="brand_id"
                            v-model="form.brand_id"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary cursor-pointer transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light"
                            :class="errors.brand_id ? 'border-accent-error' : ''"
                        >
                            <option value="">{{ $t('product.selectBrand') }}</option>
                            <option v-for="brand in brands" :key="brand.id" :value="brand.id">{{ brand.title }}</option>
                        </select>
                        <span v-if="errors.brand_id" class="block mt-1 text-xs text-accent-error">{{ errors.brand_id }}</span>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="purchase_price">
                            {{ $t('product.purchasePrice') }}
                        </label>
                        <input
                            id="purchase_price"
                            v-model="form.purchase_price"
                            type="number"
                            step="0.01"
                            min="0"
                            :placeholder="$t('product.purchasePricePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.purchase_price ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.purchase_price" class="block mt-1 text-xs text-accent-error">{{ errors.purchase_price }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="sale_price">
                            {{ $t('product.salePrice') }}
                        </label>
                        <input
                            id="sale_price"
                            v-model="form.sale_price"
                            type="number"
                            step="0.01"
                            min="0"
                            :placeholder="$t('product.salePricePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.sale_price ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.sale_price" class="block mt-1 text-xs text-accent-error">{{ errors.sale_price }}</span>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="ean13">
                            {{ $t('product.ean13') || 'EAN13' }}
                        </label>
                        <input
                            id="ean13"
                            v-model="form.ean13"
                            type="text"
                            :placeholder="$t('product.ean13Placeholder') || 'EAN13 barcode'"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.ean13 ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.ean13" class="block mt-1 text-xs text-accent-error">{{ errors.ean13 }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="unit">
                            {{ $t('product.unit') }}
                        </label>
                        <input
                            id="unit"
                            v-model="form.unit"
                            type="text"
                            :placeholder="$t('product.unitPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.unit ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.unit" class="block mt-1 text-xs text-accent-error">{{ errors.unit }}</span>
                    </div>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="description">
                        {{ $t('product.description') }}
                    </label>
                    <textarea
                        id="description"
                        v-model="form.description"
                        rows="3"
                        :placeholder="$t('product.descriptionPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary resize-none"
                        :class="errors.description ? 'border-accent-error' : ''"
                    ></textarea>
                    <span v-if="errors.description" class="block mt-1 text-xs text-accent-error">{{ errors.description }}</span>
                </div>

                <div class="grid grid-cols-3 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="isactive">
                            {{ $t('product.status') }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="isactive"
                                v-model="form.isactive"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="isactive" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.isActive') }}
                            </label>
                        </div>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="onPromo">
                            {{ $t('product.onPromo') || 'On Promotion' }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="onPromo"
                                v-model="form.onPromo"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="onPromo" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.onPromo') || 'On Promotion' }}
                            </label>
                        </div>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="isFeatured">
                            {{ $t('product.isFeatured') || 'Featured' }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="isFeatured"
                                v-model="form.isFeatured"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="isFeatured" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.isFeatured') || 'Featured' }}
                            </label>
                        </div>
                    </div>
                </div>

                <!-- Product Images Section -->
                <div class="mb-5 mt-8 pt-6 border-t border-surface-border">
                    <div class="flex justify-between items-center mb-4">
                        <h3 class="text-lg font-semibold text-text-primary m-0">{{ $t('product.images') || 'Product Images' }}</h3>
                        <label class="flex items-center gap-2 px-4 py-2 bg-accent-primary text-white rounded-lg text-sm font-medium cursor-pointer transition-all duration-200 hover:bg-accent-secondary">
                            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                <polyline points="17 8 12 3 7 8"/>
                                <line x1="12" y1="3" x2="12" y2="15"/>
                            </svg>
                            <span>{{ $t('product.selectFiles') || 'Select Files' }}</span>
                            <input
                                ref="imageFileInput"
                                type="file"
                                multiple
                                accept="image/jpeg,image/png,image/jpg,image/gif,image/webp"
                                @change="handleFilesSelect"
                                class="hidden"
                            />
                        </label>
                    </div>

                    <!-- Selected Files Preview (before upload) -->
                    <div v-if="selectedFiles.length > 0" class="mb-4">
                        <h4 class="text-sm font-medium text-text-secondary mb-3">{{ $t('product.selectedFiles') || 'Selected Files' }}</h4>
                        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                            <div v-for="(file, index) in selectedFiles" :key="index" class="relative group border-2 border-surface-border rounded-lg overflow-hidden">
                                <div class="aspect-square bg-bg-secondary flex items-center justify-center overflow-hidden">
                                    <img :src="getFilePreview(file)" :alt="file.name" class="w-full h-full object-cover" />
                                </div>
                                <div class="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center justify-center gap-2">
                                    <button @click="setSelectedFileAsPrimary(index)" class="p-2 bg-blue-500 text-white rounded hover:bg-blue-600" :title="$t('product.setPrimary') || 'Set as Primary'">
                                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                            <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                                        </svg>
                                    </button>
                                    <button @click="removeSelectedFile(index)" class="p-2 bg-red-500 text-white rounded hover:bg-red-600" :title="$t('common.remove') || 'Remove'">
                                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                            <polyline points="3 6 5 6 21 6"/>
                                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                                        </svg>
                                    </button>
                                </div>
                                <div v-if="selectedFilesPrimaryIndex === index" class="absolute top-2 left-2 bg-accent-primary text-white px-2 py-1 rounded text-xs font-semibold">
                                    {{ $t('product.primary') || 'Primary' }}
                                </div>
                                <div class="p-2 bg-bg-elevated">
                                    <p class="text-xs text-text-primary font-medium truncate">{{ file.name }}</p>
                                </div>
                            </div>
                        </div>
                        <button @click="uploadSelectedFiles" class="mt-4 px-5 py-2.5 bg-gradient-to-br from-accent-primary to-accent-secondary text-white rounded-lg font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="productImageStore.loading || selectedFiles.length === 0">
                            <span v-if="productImageStore.loading">{{ $t('common.uploading') || 'Uploading...' }}</span>
                            <span v-else>{{ $t('product.uploadImages') || 'Upload Images' }}</span>
                        </button>
                    </div>

                    <!-- Existing Images -->
                    <div v-if="productImages.length > 0" class="mt-4">
                        <h4 class="text-sm font-medium text-text-secondary mb-3">{{ $t('product.existingImages') || 'Existing Images' }}</h4>
                        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                            <div v-for="image in productImages" :key="image.id" class="relative group border-2 rounded-lg overflow-hidden" :class="image.isprimary ? 'border-accent-primary' : 'border-surface-border'">
                                <div class="aspect-square bg-bg-secondary flex items-center justify-center overflow-hidden">
                                    <img :src="image.url" :alt="image.alt || image.title" class="w-full h-full object-cover" />
                                </div>
                                <div v-if="image.isprimary" class="absolute top-2 left-2 bg-accent-primary text-white px-2 py-1 rounded text-xs font-semibold">
                                    {{ $t('product.primary') || 'Primary' }}
                                </div>
                                <div class="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center justify-center gap-2">
                                    <button @click="setAsPrimary(image.id)" v-if="!image.isprimary" class="p-2 bg-blue-500 text-white rounded hover:bg-blue-600" :title="$t('product.setPrimary') || 'Set as Primary'">
                                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                            <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                                        </svg>
                                    </button>
                                    <button @click="deleteImage(image.id)" class="p-2 bg-red-500 text-white rounded hover:bg-red-600" :title="$t('common.remove') || 'Remove'">
                                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                            <polyline points="3 6 5 6 21 6"/>
                                            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                                        </svg>
                                    </button>
                                </div>
                                <div class="p-2 bg-bg-elevated">
                                    <p class="text-xs text-text-primary font-medium truncate">{{ image.title || 'Untitled' }}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div v-if="productImages.length === 0 && selectedFiles.length === 0" class="text-center py-8 text-text-tertiary">
                        <p>{{ $t('product.noImages') || 'No images added yet' }}</p>
                    </div>
                </div>


                <div class="flex justify-end gap-3 mt-6 pt-6 border-t border-surface-border">
                    <router-link to="/app/products" class="px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                        {{ $t('common.cancel') }}
                    </router-link>
                    <button type="submit" class="px-5 py-2.5 border-none rounded-lg bg-gradient-to-br from-accent-primary to-accent-secondary text-text-inverse font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="productStore.loading">
                        <span v-if="productStore.loading">{{ $t('common.saving') }}...</span>
                        <span v-else>{{ $t('common.update') }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useProductStore } from '@/stores/product';
import { useProductImageStore } from '@/stores/productImage';
import { useCategoryStore } from '@/stores/category';
import { useBrandStore } from '@/stores/brand';
import { useToast } from '@/composables/useToast';
import { useI18n } from 'vue-i18n';

const route = useRoute();
const router = useRouter();
const productStore = useProductStore();
const productImageStore = useProductImageStore();
const categoryStore = useCategoryStore();
const brandStore = useBrandStore();
const { success, error } = useToast();
const { t } = useI18n();

const product = ref(null);
const loading = ref(true);
const categories = ref([]);
const brands = ref([]);
const productImages = ref([]);
const selectedFiles = ref([]);
const selectedFilesPrimaryIndex = ref(null);
const imageFileInput = ref(null);

const form = ref({
    name: '',
    ean13: '',
    category_id: '',
    brand_id: '',
    purchase_price: '',
    sale_price: '',
    description: '',
    tax_id: '',
    unit: '',
    isactive: true,
    onPromo: false,
    isFeatured: false
});

const errors = ref({});

onMounted(async () => {
    // Load categories and brands
    await categoryStore.fetchCategories({ per_page: 100 });
    await brandStore.fetchBrands({ per_page: 100 });
    categories.value = categoryStore.categories;
    brands.value = brandStore.brands;

    // Load product
    const productId = route.params.id;
    const result = await productStore.fetchProduct(productId);
    
    if (result.success) {
        product.value = result.data;
        form.value = {
            name: product.value.name || '',
            ean13: product.value.ean13 || '',
            category_id: product.value.category_id || '',
            brand_id: product.value.brand_id || '',
            purchase_price: product.value.purchase_price || '',
            sale_price: product.value.sale_price || '',
            description: product.value.description || '',
            tax_id: product.value.tax_id || '',
            unit: product.value.unit || '',
            isactive: product.value.isactive !== undefined ? product.value.isactive : true,
            onPromo: product.value.onPromo !== undefined ? product.value.onPromo : false,
            isFeatured: product.value.isFeatured !== undefined ? product.value.isFeatured : false
        };

        // Load product images
        await loadImages(productId);
    } else {
        error(result.error || t('product.loadFailed') || 'Failed to load product');
    }
    
    loading.value = false;
});

const loadImages = async (productId) => {
    const result = await productImageStore.fetchImages(productId);
    if (result.success) {
        productImages.value = productImageStore.images;
    }
};


const handleFilesSelect = (event) => {
    const files = Array.from(event.target.files);
    const validFiles = [];
    
    files.forEach(file => {
        // Validate file size (5MB max)
        if (file.size > 5 * 1024 * 1024) {
            error(t('product.imageFileTooLarge', { name: file.name }) || `Image file "${file.name}" is too large. Maximum size is 5MB.`);
            return;
        }
        // Validate file type
        const validTypes = ['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'image/webp'];
        if (!validTypes.includes(file.type)) {
            error(t('product.imageFileInvalidType', { name: file.name }) || `Invalid image type for "${file.name}". Please select a JPEG, PNG, GIF, or WebP image.`);
            return;
        }
        validFiles.push(file);
    });

    // Add valid files to selected files
    selectedFiles.value = [...selectedFiles.value, ...validFiles];
    
    // Set first file as primary if no primary is set
    if (selectedFilesPrimaryIndex.value === null && selectedFiles.value.length > 0) {
        selectedFilesPrimaryIndex.value = 0;
    }

    // Reset input
    if (imageFileInput.value) {
        imageFileInput.value.value = '';
    }
};

const getFilePreview = (file) => {
    return URL.createObjectURL(file);
};

const setSelectedFileAsPrimary = (index) => {
    selectedFilesPrimaryIndex.value = index;
};

const removeSelectedFile = (index) => {
    // Revoke object URL to free memory
    if (selectedFiles.value[index]) {
        URL.revokeObjectURL(getFilePreview(selectedFiles.value[index]));
    }
    selectedFiles.value.splice(index, 1);
    if (selectedFilesPrimaryIndex.value === index) {
        selectedFilesPrimaryIndex.value = selectedFiles.value.length > 0 ? 0 : null;
    } else if (selectedFilesPrimaryIndex.value > index) {
        selectedFilesPrimaryIndex.value--;
    }
};

const uploadSelectedFiles = async () => {
    if (selectedFiles.value.length === 0) {
        return;
    }

    const productId = product.value.id;
    const result = await productImageStore.uploadMultipleImages(productId, selectedFiles.value, selectedFilesPrimaryIndex.value);

    if (result.success) {
        success(t('product.imagesUploaded') || 'Images uploaded successfully');
        await loadImages(productId);
        // Clear selected files and revoke object URLs
        selectedFiles.value.forEach(file => {
            URL.revokeObjectURL(getFilePreview(file));
        });
        selectedFiles.value = [];
        selectedFilesPrimaryIndex.value = null;
    } else {
        error(result.error || t('product.imagesUploadFailed') || 'Failed to upload images');
    }
};

const setAsPrimary = async (imageId) => {
    const productId = product.value.id;
    const result = await productImageStore.setPrimaryImage(productId, imageId);
    if (result.success) {
        success(t('product.primaryImageSet') || 'Primary image set successfully');
        await loadImages(productId);
    } else {
        error(result.error || t('product.primaryImageSetFailed') || 'Failed to set primary image');
    }
};

const deleteImage = async (imageId) => {
    const confirmMessage = t('product.confirmDeleteImage') || 'Are you sure you want to delete this image?';
    if (!confirm(confirmMessage)) {
        return;
    }

    const productId = product.value.id;
    const result = await productImageStore.deleteImage(productId, imageId);
    if (result.success) {
        success(t('product.imageDeleted') || 'Image deleted successfully');
        await loadImages(productId);
    } else {
        error(result.error || t('product.imageDeleteFailed') || 'Failed to delete image');
    }
};

const handleSubmit = async () => {
    errors.value = {};

    if (!form.value.name.trim()) {
        errors.value.name = t('product.nameRequired');
        return;
    }

    const productData = {
        name: form.value.name.trim(),
        ean13: form.value.ean13 || null,
        category_id: form.value.category_id || null,
        brand_id: form.value.brand_id || null,
        purchase_price: form.value.purchase_price ? parseFloat(form.value.purchase_price) : 0,
        sale_price: form.value.sale_price ? parseFloat(form.value.sale_price) : 0,
        description: form.value.description || null,
        tax_id: form.value.tax_id || null,
        unit: form.value.unit || null,
        isactive: form.value.isactive,
        onPromo: form.value.onPromo,
        isFeatured: form.value.isFeatured
    };

    const result = await productStore.updateProduct(product.value.id, productData);

    if (result.success) {
        success(t('product.updated'));
        router.push('/app/products');
    } else {
        error(result.error || t('product.updateFailed'));
        if (result.errors) {
            errors.value = result.errors;
        }
    }
};
</script>

