<template>
    <div v-if="show" class="fixed inset-0 bg-black/60 dark:bg-black/80 flex items-center justify-center z-[1000] p-5" @click.self="handleClose">
        <div class="bg-bg-elevated rounded-xl w-full max-w-[700px] max-h-[90vh] overflow-y-auto shadow-xl border border-surface-border">
            <div class="flex justify-between items-center p-6 border-b border-surface-border sticky top-0 bg-bg-elevated z-10">
                <h2 class="text-xl font-semibold text-text-primary m-0">
                    {{ product ? $t('product.edit') : $t('product.create') }}
                </h2>
                <button @click="handleClose" class="bg-transparent border-none text-text-secondary cursor-pointer p-1 rounded transition-all duration-200 hover:bg-surface-hover hover:text-text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="18" y1="6" x2="6" y2="18"/>
                        <line x1="6" y1="6" x2="18" y2="18"/>
                    </svg>
                </button>
            </div>

            <form @submit.prevent="handleSubmit" class="p-6">
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2">{{ $t('product.code') }}</label>
                    <input
                        type="text"
                        :value="product?.code || $t('product.autoGenerated')"
                        disabled
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-tertiary text-text-disabled cursor-not-allowed"
                    />
                    <small class="block mt-1 text-xs text-text-tertiary">{{ $t('product.codeHint') }}</small>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="name">
                        {{ $t('product.name') }} <span class="text-accent-error">*</span>
                    </label>
                    <input
                        id="name"
                        v-model="form.name"
                        type="text"
                        :placeholder="$t('product.namePlaceholder')"
                        required
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        :class="errors.name ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    />
                    <span v-if="errors.name" class="block mt-1 text-xs text-accent-error">{{ errors.name }}</span>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="category_id">
                            {{ $t('product.category') }}
                        </label>
                        <select
                            id="category_id"
                            v-model="form.category_id"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary cursor-pointer transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light"
                            :class="errors.category_id ? 'border-accent-error' : ''"
                        >
                            <option value="">{{ $t('product.selectCategory') }}</option>
                            <option v-for="category in categories" :key="category.id" :value="category.id">{{ category.title }}</option>
                        </select>
                        <span v-if="errors.category_id" class="block mt-1 text-xs text-accent-error">{{ errors.category_id }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="brand_id">
                            {{ $t('product.brand') }}
                        </label>
                        <select
                            id="brand_id"
                            v-model="form.brand_id"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary cursor-pointer transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light"
                            :class="errors.brand_id ? 'border-accent-error' : ''"
                        >
                            <option value="">{{ $t('product.selectBrand') }}</option>
                            <option v-for="brand in brands" :key="brand.id" :value="brand.id">{{ brand.title }}</option>
                        </select>
                        <span v-if="errors.brand_id" class="block mt-1 text-xs text-accent-error">{{ errors.brand_id }}</span>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="purchase_price">
                            {{ $t('product.purchasePrice') }}
                        </label>
                        <input
                            id="purchase_price"
                            v-model="form.purchase_price"
                            type="number"
                            step="0.01"
                            min="0"
                            :placeholder="$t('product.purchasePricePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.purchase_price ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.purchase_price" class="block mt-1 text-xs text-accent-error">{{ errors.purchase_price }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="sale_price">
                            {{ $t('product.salePrice') }}
                        </label>
                        <input
                            id="sale_price"
                            v-model="form.sale_price"
                            type="number"
                            step="0.01"
                            min="0"
                            :placeholder="$t('product.salePricePlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.sale_price ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.sale_price" class="block mt-1 text-xs text-accent-error">{{ errors.sale_price }}</span>
                    </div>
                </div>

                <div class="grid grid-cols-2 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="ean13">
                            {{ $t('product.ean13') || 'EAN13' }}
                        </label>
                        <input
                            id="ean13"
                            v-model="form.ean13"
                            type="text"
                            :placeholder="$t('product.ean13Placeholder') || 'EAN13 barcode'"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.ean13 ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.ean13" class="block mt-1 text-xs text-accent-error">{{ errors.ean13 }}</span>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="unit">
                            {{ $t('product.unit') }}
                        </label>
                        <input
                            id="unit"
                            v-model="form.unit"
                            type="text"
                            :placeholder="$t('product.unitPlaceholder')"
                            class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                            :class="errors.unit ? 'border-accent-error' : ''"
                        />
                        <span v-if="errors.unit" class="block mt-1 text-xs text-accent-error">{{ errors.unit }}</span>
                    </div>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="description">
                        {{ $t('product.description') }}
                    </label>
                    <textarea
                        id="description"
                        v-model="form.description"
                        rows="3"
                        :placeholder="$t('product.descriptionPlaceholder')"
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary resize-none"
                        :class="errors.description ? 'border-accent-error' : ''"
                    ></textarea>
                    <span v-if="errors.description" class="block mt-1 text-xs text-accent-error">{{ errors.description }}</span>
                </div>

                <div class="grid grid-cols-3 gap-4 mb-5">
                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="isactive">
                            {{ $t('product.status') }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="isactive"
                                v-model="form.isactive"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="isactive" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.isActive') }}
                            </label>
                        </div>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="onPromo">
                            {{ $t('product.onPromo') || 'On Promotion' }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="onPromo"
                                v-model="form.onPromo"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="onPromo" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.onPromo') || 'On Promotion' }}
                            </label>
                        </div>
                    </div>

                    <div>
                        <label class="block text-sm font-medium text-text-secondary mb-2" for="isFeatured">
                            {{ $t('product.isFeatured') || 'Featured' }}
                        </label>
                        <div class="flex items-center gap-2">
                            <input
                                id="isFeatured"
                                v-model="form.isFeatured"
                                type="checkbox"
                                class="w-[18px] h-[18px] cursor-pointer"
                            />
                            <label for="isFeatured" class="text-sm text-text-secondary cursor-pointer">
                                {{ $t('product.isFeatured') || 'Featured' }}
                            </label>
                        </div>
                    </div>
                </div>

                <div class="flex justify-end gap-3 mt-6 pt-6 border-t border-surface-border">
                    <button type="button" @click="handleClose" class="px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                        {{ $t('common.cancel') }}
                    </button>
                    <button type="submit" class="px-5 py-2.5 border-none rounded-lg bg-gradient-to-br from-accent-primary to-accent-secondary text-text-inverse font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="productStore.loading">
                        <span v-if="productStore.loading">{{ $t('common.saving') }}...</span>
                        <span v-else>{{ product ? $t('common.update') : $t('common.create') }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, watch, onMounted } from 'vue';
import { useProductStore } from '@/stores/product';
import { useCategoryStore } from '@/stores/category';
import { useBrandStore } from '@/stores/brand';
import { useToast } from '@/composables/useToast';
import { useI18n } from 'vue-i18n';

const props = defineProps({
    show: {
        type: Boolean,
        default: false
    },
    product: {
        type: Object,
        default: null
    }
});

const emit = defineEmits(['close', 'saved']);

const productStore = useProductStore();
const categoryStore = useCategoryStore();
const brandStore = useBrandStore();
const { success, error } = useToast();
const { t } = useI18n();

const categories = ref([]);
const brands = ref([]);

const form = ref({
    name: '',
    ean13: '',
    category_id: '',
    brand_id: '',
    purchase_price: '',
    sale_price: '',
    description: '',
    tax_id: '',
    unit: '',
    isactive: true,
    onPromo: false,
    isFeatured: false
});

const errors = ref({});

onMounted(async () => {
    await categoryStore.fetchCategories({ per_page: 100 });
    await brandStore.fetchBrands({ per_page: 100 });
    categories.value = categoryStore.categories;
    brands.value = brandStore.brands;
});

watch(() => props.product, (newProduct) => {
    if (newProduct) {
        form.value = {
            name: newProduct.name || '',
            ean13: newProduct.ean13 || '',
            category_id: newProduct.category_id || '',
            brand_id: newProduct.brand_id || '',
            purchase_price: newProduct.purchase_price || '',
            sale_price: newProduct.sale_price || '',
            description: newProduct.description || '',
            tax_id: newProduct.tax_id || '',
            unit: newProduct.unit || '',
            isactive: newProduct.isactive !== undefined ? newProduct.isactive : true,
            onPromo: newProduct.onPromo !== undefined ? newProduct.onPromo : false,
            isFeatured: newProduct.isFeatured !== undefined ? newProduct.isFeatured : false
        };
    } else {
        form.value = {
            name: '',
            ean13: '',
            category_id: '',
            brand_id: '',
            purchase_price: '',
            sale_price: '',
            description: '',
            tax_id: '',
            unit: '',
            isactive: true,
            onPromo: false,
            isFeatured: false
        };
    }
    errors.value = {};
}, { immediate: true });

watch(() => props.show, (isShow) => {
    if (isShow && props.product) {
        form.value = {
            name: props.product.name || '',
            ean13: props.product.ean13 || '',
            category_id: props.product.category_id || '',
            brand_id: props.product.brand_id || '',
            purchase_price: props.product.purchase_price || '',
            sale_price: props.product.sale_price || '',
            description: props.product.description || '',
            tax_id: props.product.tax_id || '',
            unit: props.product.unit || '',
            isactive: props.product.isactive !== undefined ? props.product.isactive : true,
            onPromo: props.product.onPromo !== undefined ? props.product.onPromo : false,
            isFeatured: props.product.isFeatured !== undefined ? props.product.isFeatured : false
        };
    } else if (isShow && !props.product) {
        form.value = {
            name: '',
            ean13: '',
            category_id: '',
            brand_id: '',
            purchase_price: '',
            sale_price: '',
            description: '',
            tax_id: '',
            unit: '',
            isactive: true,
            onPromo: false,
            isFeatured: false
        };
    }
    errors.value = {};
});

const handleClose = () => {
    emit('close');
    form.value = {
        name: '',
        ean13: '',
        category_id: '',
        brand_id: '',
        purchase_price: '',
        sale_price: '',
        description: '',
        tax_id: '',
        unit: '',
        isactive: true,
        onPromo: false,
        isFeatured: false
    };
    errors.value = {};
};

const handleSubmit = async () => {
    errors.value = {};

    if (!form.value.name.trim()) {
        errors.value.name = t('product.nameRequired');
        return;
    }

    const productData = {
        name: form.value.name.trim(),
        ean13: form.value.ean13 || null,
        category_id: form.value.category_id || null,
        brand_id: form.value.brand_id || null,
        purchase_price: form.value.purchase_price ? parseFloat(form.value.purchase_price) : 0,
        sale_price: form.value.sale_price ? parseFloat(form.value.sale_price) : 0,
        description: form.value.description || null,
        tax_id: form.value.tax_id || null,
        unit: form.value.unit || null,
        isactive: form.value.isactive,
        onPromo: form.value.onPromo,
        isFeatured: form.value.isFeatured
    };

    let result;
    if (props.product) {
        result = await productStore.updateProduct(props.product.id, productData);
    } else {
        result = await productStore.createProduct(productData);
    }

    if (result.success) {
        success(props.product ? t('product.updated') : t('product.created'));
        emit('saved');
    } else {
        error(result.error || (props.product ? t('product.updateFailed') : t('product.createFailed')));
        if (result.errors) {
            errors.value = result.errors;
        }
    }
};
</script>

