<template>
    <div v-if="show" class="fixed inset-0 bg-black/60 dark:bg-black/80 flex items-center justify-center z-[1000] p-5" @click.self="handleClose">
        <div class="bg-bg-elevated rounded-xl w-full max-w-[500px] max-h-[90vh] overflow-y-auto shadow-xl border border-surface-border">
            <div class="flex justify-between items-center p-6 border-b border-surface-border">
                <h2 class="text-xl font-semibold text-text-primary m-0">
                    {{ category ? $t('category.edit') : $t('category.create') }}
                </h2>
                <button @click="handleClose" class="bg-transparent border-none text-text-secondary cursor-pointer p-1 rounded transition-all duration-200 hover:bg-surface-hover hover:text-text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="18" y1="6" x2="6" y2="18"/>
                        <line x1="6" y1="6" x2="18" y2="18"/>
                    </svg>
                </button>
            </div>

            <form @submit.prevent="handleSubmit" class="p-6">
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2">{{ $t('category.code') }}</label>
                    <input
                        type="text"
                        :value="category?.code || $t('category.autoGenerated')"
                        disabled
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-tertiary text-text-disabled cursor-not-allowed"
                    />
                    <small class="block mt-1 text-xs text-text-tertiary">{{ $t('category.codeHint') }}</small>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="title">
                        {{ $t('category.title') }} <span class="text-accent-error">*</span>
                    </label>
                    <input
                        id="title"
                        v-model="form.title"
                        type="text"
                        :placeholder="$t('category.titlePlaceholder')"
                        required
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        :class="errors.title ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    />
                    <span v-if="errors.title" class="block mt-1 text-xs text-accent-error">{{ errors.title }}</span>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="status">
                        {{ $t('category.status') }}
                    </label>
                    <div class="flex items-center gap-2">
                        <input
                            id="status"
                            v-model="form.status"
                            type="checkbox"
                            class="w-[18px] h-[18px] cursor-pointer"
                        />
                        <label for="status" class="text-sm text-text-secondary cursor-pointer">
                            {{ $t('category.isActive') }}
                        </label>
                    </div>
                </div>

                <div class="flex justify-end gap-3 mt-6 pt-6 border-t border-surface-border">
                    <button type="button" @click="handleClose" class="px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                        {{ $t('common.cancel') }}
                    </button>
                    <button type="submit" class="px-5 py-2.5 border-none rounded-lg bg-gradient-to-br from-accent-primary to-accent-secondary text-text-inverse font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="categoryStore.loading">
                        <span v-if="categoryStore.loading">{{ $t('common.saving') }}...</span>
                        <span v-else>{{ category ? $t('common.update') : $t('common.create') }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, watch, onMounted } from 'vue';
import { useCategoryStore } from '@/stores/category';
import { useToast } from '@/composables/useToast';
import { useI18n } from 'vue-i18n';

const props = defineProps({
    show: {
        type: Boolean,
        default: false
    },
    category: {
        type: Object,
        default: null
    }
});

const emit = defineEmits(['close', 'saved']);

const categoryStore = useCategoryStore();
const { success, error } = useToast();
const { t } = useI18n();

const form = ref({
    title: '',
    status: true
});

const errors = ref({});

watch(() => props.category, (newCategory) => {
    if (newCategory) {
        form.value = {
            title: newCategory.title || '',
            status: newCategory.status !== undefined ? newCategory.status : true
        };
    } else {
        form.value = {
            title: '',
            status: true
        };
    }
    errors.value = {};
}, { immediate: true });

watch(() => props.show, (isShow) => {
    if (isShow && props.category) {
        form.value = {
            title: props.category.title || '',
            status: props.category.status !== undefined ? props.category.status : true
        };
    } else if (isShow && !props.category) {
        form.value = {
            title: '',
            status: true
        };
    }
    errors.value = {};
});

const handleClose = () => {
    emit('close');
    form.value = {
        title: '',
        status: true
    };
    errors.value = {};
};

const handleSubmit = async () => {
    errors.value = {};

    if (!form.value.title.trim()) {
        errors.value.title = t('category.titleRequired');
        return;
    }

    const categoryData = {
        title: form.value.title.trim(),
        status: form.value.status
    };

    let result;
    if (props.category) {
        result = await categoryStore.updateCategory(props.category.id, categoryData);
    } else {
        result = await categoryStore.createCategory(categoryData);
    }

    if (result.success) {
        success(props.category ? t('category.updated') : t('category.created'));
        emit('saved');
    } else {
        error(result.error || (props.category ? t('category.updateFailed') : t('category.createFailed')));
        if (result.errors) {
            errors.value = result.errors;
        }
    }
};
</script>

