<template>
    <div v-if="show" class="fixed inset-0 bg-black/60 dark:bg-black/80 flex items-center justify-center z-[1000] p-5" @click.self="handleClose">
        <div class="bg-bg-elevated rounded-xl w-full max-w-[600px] max-h-[90vh] overflow-y-auto shadow-xl border border-surface-border">
            <div class="flex justify-between items-center p-6 border-b border-surface-border">
                <h2 class="text-xl font-semibold text-text-primary m-0">
                    {{ warehouse ? $t('warehouse.edit') : $t('warehouse.create') }}
                </h2>
                <button @click="handleClose" class="bg-transparent border-none text-text-secondary cursor-pointer p-1 rounded transition-all duration-200 hover:bg-surface-hover hover:text-text-primary">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="18" y1="6" x2="6" y2="18"/>
                        <line x1="6" y1="6" x2="18" y2="18"/>
                    </svg>
                </button>
            </div>

            <form @submit.prevent="handleSubmit" class="p-6">
                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2">{{ $t('warehouse.code') }}</label>
                    <input
                        type="text"
                        :value="warehouse?.code || $t('warehouse.autoGenerated')"
                        disabled
                        class="w-full py-2.5 px-3 border-2 border-surface-border rounded-lg text-sm bg-bg-tertiary text-text-disabled cursor-not-allowed"
                    />
                    <small class="block mt-1 text-xs text-text-tertiary">{{ $t('warehouse.codeHint') }}</small>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="title">
                        {{ $t('warehouse.title') }} <span class="text-accent-error">*</span>
                    </label>
                    <input
                        id="title"
                        v-model="form.title"
                        type="text"
                        :placeholder="$t('warehouse.titlePlaceholder')"
                        required
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light placeholder:text-text-tertiary"
                        :class="errors.title ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    />
                    <span v-if="errors.title" class="block mt-1 text-xs text-accent-error">{{ errors.title }}</span>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="type">
                        {{ $t('warehouse.type') }} <span class="text-accent-error">*</span>
                    </label>
                    <select
                        id="type"
                        v-model="form.type"
                        required
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light cursor-pointer"
                        :class="errors.type ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    >
                        <option value="">{{ $t('warehouse.selectType') }}</option>
                        <option value="warehouse">{{ $t('warehouse.typeWarehouse') }}</option>
                        <option value="store">{{ $t('warehouse.typeStore') }}</option>
                        <option value="tank">{{ $t('warehouse.typeTank') }}</option>
                    </select>
                    <span v-if="errors.type" class="block mt-1 text-xs text-accent-error">{{ errors.type }}</span>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="inchargeOf">
                        {{ $t('warehouse.inchargeOf') }}
                    </label>
                    <select
                        id="inchargeOf"
                        v-model="form.inchargeOf"
                        class="w-full py-2.5 px-3 border-2 rounded-lg text-sm bg-bg-primary text-text-primary transition-all duration-200 focus:outline-none focus:border-border-focus focus:ring-2 focus:ring-accent-primary-light cursor-pointer"
                        :class="errors.inchargeOf ? 'border-accent-error focus:ring-red-200' : 'border-surface-border'"
                    >
                        <option :value="null">{{ $t('warehouse.noIncharge') }}</option>
                        <option v-for="user in users" :key="user.id" :value="user.id">
                            {{ user.name }} ({{ user.email }})
                        </option>
                    </select>
                    <span v-if="errors.inchargeOf" class="block mt-1 text-xs text-accent-error">{{ errors.inchargeOf }}</span>
                </div>

                <div class="mb-5">
                    <label class="block text-sm font-medium text-text-secondary mb-2" for="isprincipal">
                        {{ $t('warehouse.isprincipal') }}
                    </label>
                    <div class="flex items-center gap-2">
                        <input
                            id="isprincipal"
                            v-model="form.isprincipal"
                            type="checkbox"
                            class="w-[18px] h-[18px] cursor-pointer"
                        />
                        <label for="isprincipal" class="text-sm text-text-secondary cursor-pointer">
                            {{ $t('warehouse.markAsPrincipal') }}
                        </label>
                    </div>
                </div>

                <div class="flex justify-end gap-3 mt-6 pt-6 border-t border-surface-border">
                    <button type="button" @click="handleClose" class="px-5 py-2.5 border-2 border-surface-border rounded-lg bg-bg-primary text-text-primary font-medium cursor-pointer transition-all duration-200 hover:border-border-hover hover:bg-surface-hover">
                        {{ $t('common.cancel') }}
                    </button>
                    <button type="submit" class="px-5 py-2.5 border-none rounded-lg bg-gradient-to-br from-accent-primary to-accent-secondary text-text-inverse font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg hover:brightness-110 disabled:opacity-60 disabled:cursor-not-allowed" :disabled="warehouseStore.loading">
                        <span v-if="warehouseStore.loading">{{ $t('common.saving') }}...</span>
                        <span v-else>{{ warehouse ? $t('common.update') : $t('common.create') }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>

<script setup>
import { ref, watch, onMounted } from 'vue';
import { useWarehouseStore } from '@/stores/warehouse';
import { useToast } from '@/composables/useToast';
import { useI18n } from 'vue-i18n';

const props = defineProps({
    show: {
        type: Boolean,
        default: false
    },
    warehouse: {
        type: Object,
        default: null
    }
});

const emit = defineEmits(['close', 'saved']);

const warehouseStore = useWarehouseStore();
const { success, error } = useToast();
const { t } = useI18n();

const form = ref({
    title: '',
    type: 'warehouse',
    inchargeOf: null,
    isprincipal: false
});

const errors = ref({});
const users = ref([]);
const loadingUsers = ref(false);

// Helper function to get CSRF token
const getCsrfToken = () => {
    return document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '';
};

// Helper function to get headers
const getHeaders = () => {
    return {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'X-CSRF-TOKEN': getCsrfToken()
    };
};

// Fetch users for dropdown
const fetchUsers = async () => {
    if (users.value.length > 0) return; // Already loaded
    
    loadingUsers.value = true;
    try {
        // Try to fetch from /api/users endpoint, or use a simple approach
        // For now, we'll create a simple endpoint or use existing user data
        const response = await fetch('/api/users', {
            method: 'GET',
            headers: getHeaders(),
            credentials: 'include'
        });

        if (response.ok) {
            const data = await response.json();
            if (data.success && Array.isArray(data.data)) {
                users.value = data.data;
            } else if (Array.isArray(data)) {
                users.value = data;
            }
        }
    } catch (err) {
        console.error('Failed to fetch users:', err);
        // If endpoint doesn't exist, we'll handle it gracefully
        users.value = [];
    } finally {
        loadingUsers.value = false;
    }
};

onMounted(() => {
    fetchUsers();
});

watch(() => props.warehouse, (newWarehouse) => {
    if (newWarehouse) {
        form.value = {
            title: newWarehouse.title || '',
            type: newWarehouse.type || 'warehouse',
            inchargeOf: newWarehouse.inchargeOf || null,
            isprincipal: newWarehouse.isprincipal !== undefined ? newWarehouse.isprincipal : false
        };
    } else {
        form.value = {
            title: '',
            type: 'warehouse',
            inchargeOf: null,
            isprincipal: false
        };
    }
    errors.value = {};
}, { immediate: true });

watch(() => props.show, (isShow) => {
    if (isShow) {
        fetchUsers();
        if (props.warehouse) {
            form.value = {
                title: props.warehouse.title || '',
                type: props.warehouse.type || 'warehouse',
                inchargeOf: props.warehouse.inchargeOf || null,
                isprincipal: props.warehouse.isprincipal !== undefined ? props.warehouse.isprincipal : false
            };
        } else {
            form.value = {
                title: '',
                type: 'warehouse',
                inchargeOf: null,
                isprincipal: false
            };
        }
        errors.value = {};
    }
});

const handleClose = () => {
    emit('close');
    form.value = {
        title: '',
        type: 'warehouse',
        inchargeOf: null,
        isprincipal: false
    };
    errors.value = {};
};

const handleSubmit = async () => {
    errors.value = {};

    if (!form.value.title.trim()) {
        errors.value.title = t('warehouse.titleRequired');
        return;
    }

    if (!form.value.type) {
        errors.value.type = t('warehouse.typeRequired');
        return;
    }

    const warehouseData = {
        title: form.value.title.trim(),
        type: form.value.type,
        inchargeOf: form.value.inchargeOf || null,
        isprincipal: form.value.isprincipal
    };

    let result;
    if (props.warehouse) {
        result = await warehouseStore.updateWarehouse(props.warehouse.id, warehouseData);
    } else {
        result = await warehouseStore.createWarehouse(warehouseData);
    }

    if (result.success) {
        success(props.warehouse ? t('warehouse.updated') : t('warehouse.created'));
        emit('saved');
    } else {
        error(result.error || (props.warehouse ? t('warehouse.updateFailed') : t('warehouse.createFailed')));
        if (result.errors) {
            errors.value = result.errors;
        }
    }
};
</script>
